function L = lap(n, dx, dy, dz)
%LAP_N Summary of this function goes here
%   Detailed explanation goes here
L =     ( ... 
        (circshift(n(:,:,:), [ 1,0,0]) ...
        +circshift(n(:,:,:), [-1,0,0]) - ...
        2*n(:,:,:) )/dx + ...
        (circshift(n(:,:,:), [0, 1,0]) ...
        +circshift(n(:,:,:), [0,-1,0]) - ...
        2*n(:,:,:) )/dy + ...
        (circshift(n(:,:,:), [0,0, 1]) ...
        +circshift(n(:,:,:), [0,0,-1]) - ...
        2*n(:,:,:) )/dz ...
        );
end

